name: credit_vae
channels:
  - defaults
  - pytorch

dependencies:
  - pytorch=2.4.1=py3.8_cpu_0
  - torchvision=0.19.1=py38_cpu
  - torchaudio=2.4.1=py38_cpu
  - numpy=1.24.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - pillow=10.4.0
  - networkx=3.1
  - sympy=1.13.2
  - requests=2.32.3
  - pyyaml=6.0.1
  - jinja2=3.1.4
  - markupsafe=2.1.3
  - typing_extensions=4.11.0
  - pandas=1.4.1

